### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by rohitkandhal** [stef-levesque/vscode-perforce#14]
I get following error while running any node related command like `npm -v`, `npm install`, `gulp -v`:

```
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^
Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:263:17)
    at Function.Module._resolveFilename (module.js:330:31)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:26:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:413:34)

```

**Comment by stef-levesque** [comment]
This seems related to your npm installation, not the vscode-perforce project
